#spring.cloud.gateway.enabled=false
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
#        - id: Student-Service
#          uri: lb://student-service
#          predicates:
#            - Path=/api/users/**
#        - id: Course-Service
#          uri: lb://course-service
#          predicates:
#            - Path=/api/courses/**
#        - id: Inscription-Service
#          uri: lb://inscription-service
#          predicates:
#            - Path=/api/inscriptionsOpenFeign/**
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080